config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pokemons#index'
  resources :pokemons, only: [:index]

  post 'list', to: 'pokemons#list'
  get 'list', to: 'pokemons#list'

  post 'upload', to: 'pokemons#upload'
  delete 'destroy', to: 'pokemons#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon

  require 'csv'

  def index
    @pokemons = Pokemon.all
  end

  def list
    if(params[:pokemon] && params[:pokemon][:limit])
      @pokemon_limit = params[:pokemon][:limit].to_i
    end
  end

  def upload
    csv_path = File.join(Rails.root, 'db', 'pokemon.csv')
    PokemonAddWorker.perform_async(csv_path)
    
    flash[:notice] = "Adding Pokemon to the db.."
    redirect_to root_path
  end

  def destroy
    PokemonRemoveWorker.perform_async
    flash[:notice] = "Removing Pokemon from the db..."
    redirect_to root_path
  end

  private

  def set_pokemon
    @pokemons = Pokemon.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedex</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/_messages.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
      <br>
    <% end %>
    
  </div>
</div>

app/views/pokemons/index.html.erb
<%= render 'messages' %>

<h2>Pokemon</h2>

<% if !@pokemons.any?%>
  <%= button_to 'Upload Pokemon!', upload_path %>
<% else %>
  <%= button_to 'Delete all', destroy_path, method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>

<table id='pokedex_table'>
  <tr>
    <th>Pokedex #</th>
    <th>Pokemon</th>
    <th>Height</th>
    <th>Weight</th>
    <th>Base Exp</th>
  </tr>
  <% @pokemons.each do |pokemon| %>
    <tr>
      <th><%= pokemon.number %></th>
      <th><%= pokemon.name %></th>
      <th><%= pokemon.height %></th>
      <th><%= pokemon.weight %></th>
      <th><%= pokemon.base_exp %></th>
    </tr>
  <% end %>
</table>

app/views/pokemons/list.html.erb
<%= render 'messages' %>
<%= link_to 'Home', root_path %>
<ul>
  <% @pokemons.each do |pokemon| %>
    <li><%= pokemon.name.capitalize %></li>
    <% break if pokemon.number == @pokemon_limit %>
  <% end %>
</ul>